### ISSUE TITLE
Missing dist folder in version 1.0.2

### ISSUE THREAD

**Issue by boostvolt** [danestves/lite-embed#79]
I think you forgot to publish the dist folder in version 1.0.2. Accordingly, only the readme, license and package.json are included in the dependency.

![Version 1.0.2](https://user-images.githubusercontent.com/51777660/168662872-e840baef-b90c-4ac3-bd84-2cdaae3227e0.png)

**Comment by jonurq** [comment]
+1

**Comment by danestves** [comment]
Let me see what is the error

**Comment by danestves** [comment]
It should be fixed on `v1.0.4` https://github.com/danestves/lite-embed/releases/tag/v1.0.4
