### ISSUE TITLE
Not working with NextJS

### ISSUE THREAD

**Issue by dgknca** [danestves/lite-embed#80]
React v18.2.0
Next v12.2.5
Node v16.16.0

<img width="986" alt="Screen Shot 2022-08-14 at 19 10 38" src="https://user-images.githubusercontent.com/38227845/184545528-f604ed4f-1a2d-4e46-9a66-f2bb2664f896.png">

**Comment by nicky-ru** [comment]
Same here

**Comment by danestves** [comment]
Can you guys post a reproduction of the bug on https://next.new?

**Comment by briannelson95** [comment]
I see that this was close but I'm still getting this error with Next. Was there a fix? If so what was the fix?
